version: '2'
services:
  adevav:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - './:/app'
    links:
      - server
    privileged: true
  server:
    image: creativopty/adevav-back-end:latest
    links:
      - 'mysql'
    ports:
      - '3001:3001'
    environment:
      DB_USER: 'root'
      DB_PASSWORD: 'adevav_2016'
      DB_NAME: 'adevav'
      DB_HOST: 'mysql'
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql:5.5'
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=adevav_2016
      - MYSQL_DATABASE=adevav
